### ISSUE TITLE
Результаты запуска положите в виже скриншота в папку results - не увидел

### ISSUE THREAD

**Issue by tallinn-learning** [ViolettaKL/HWLesson9#1]
https://github.com/ViolettaKL/HWLesson9/blob/6371ee7abc6b37c025d1bc8e6158be04c3bf18f2/src/test/java/org/example/InsuranceTest.java#L1

**Comment by ViolettaKL** [comment]
Создала папку results и положила туда скрин

**Comment by tallinn-learning** [comment]
Пожалуйста не закрывайте issue сами - принято что его закрывает тот, кто открыл после того как убедился что он исправлен
